#!/bin/bash
# Chezmoi script: Post-apply notification

echo ""
echo "==================================="
echo "✅ Dotfiles applied successfully!"
echo "==================================="
echo ""
echo "Next steps:"
echo ""
echo "1. Restart your terminal or run:"
echo "   source ~/.zshrc"
echo ""
echo "2. To initialize local configuration:"
echo "   cp ~/.config/zsh/local.zsh.example ~/.config/zsh/local.zsh"
echo "   Then edit ~/.config/zsh/local.zsh to add machine-specific settings"
echo ""
echo "3. To import history to Atuin:"
echo "   atuin import auto"
echo ""
echo "4. To launch kanata:"
echo "   ~/dotfiles/scripts/run_kanata.sh"
echo ""
echo "5. To initialize nvim (LazyVim):"
echo "   Plugins will auto-download on first nvim launch"
echo "   Run: nvim"
echo "   Wait for plugin installation (press q to exit startup screen)"
echo ""
echo "Common commands:"
echo "   chezmoi edit ~/.zshrc     # Edit configuration"
echo "   chezmoi diff              # View changes"
echo "   chezmoi apply             # Apply changes"
echo "   chezmoi update            # Pull and apply latest"
echo ""
echo "==================================="
